version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
